config/routes.rb
Ryte::Application.routes.draw do

  resources :posts do
    get :all, on: :collection
  end

  match '/tags/:name' => 'tags#by_name', as: :tag

  root :to => 'welcome#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/post.rb
class Post
  include ActionView::Helpers::SanitizeHelper

  attr_accessor :attributes

  def initialize(attributes = {})
    @attributes = attributes
    @id         = attributes['ID'] || attributes['id']
    @title      = attributes['title']
    @body       = attributes['content']
    @excerpt    = attributes['excerpt']
    @date       = Date.parse attributes['date']
    @tags       = attributes['tags']
    @type       = attributes['type'] || "text"
    @caption    = attributes['caption']
    unless attributes['photos'].blank?
      @photos     = attributes['photos'].map {|hash| Photo.new(hash["original_size"]) }
    end
  end

  #
  # @group type
  #

  def text?
    @type == "text"
  end

  def photo?
    @type == "photo"
  end

  #
  # @group id
  #

  def id
    @id
  end

  alias :to_param :id

  #
  # @group photos
  #

  def photos
    @photos
  end

  def photo
    photos.first
  end

  #
  # @group caption
  #

  def caption
    @caption
  end

  def caption?
    @caption.present?
  end

  #
  # @group tags
  #

  def tags?
    @tags.present?
  end

  def tags
    @tags
  end

  #
  # @group content
  #

  def show_more?
    @body.present?
  end

  def excerpt
    @excerpt
  end

  def body
    @body
  end

  #
  # @group meta
  #

  def formatted_date
    @date.strftime("%B %d, %Y")
  end

  def meta_description
    strip_tags(@body)[0..150]
  end

  def keywords
    @tags.values.join(", ")
  end

  def title
    @title
  end

  class NoBloggingPlatform < Exception; end

  class << self
    def source
      if ::Wordpress.enabled?
        ::Wordpress
      elsif ::Tumblr.enabled?
        ::Tumblr
      else
        raise NoBloggingPlatform.new("No blogging platform has been picked!")
      end
    end

    def find(post_id)
      new(source.find(post_id))
    end

    def all
      source.posts.map do |post|
        Post.new(post)
      end
    end
  end
end

app/controllers/posts_controller.rb
require 'wordpress'
require 'tumblr'

class PostsController < ApplicationController
  layout false

  def show
    @post = Post.find(params[:id])
  end

  def index
    render json: {
      html: render_to_string(action: "index", controller: "posts")
    }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_photo.html.erb
<article id="<%= post.id %>">
  <hgroup>
    <!--
        <h2><a href="/post/{{ id }}">Photo</a></h2>
        -->
    <h3><a href="#<%= post.id %>"><%= post.formatted_date %></a></h3>
  </hgroup>

  <% post.photos.each do |photo| %>
    <p><img src="<%= photo['url'] %>" width="<%= photo['width'] %>" height="<%= photo['height'] %>" /></p>
    <% if photo.caption? %>
      <%= raw photo.caption %>
    <% end %>
  <% end %>

  <% if post.caption? %>
    <%= raw post.caption %>
  <% end %>

  <footer>
    <% if post.tags? %>
      <h4>Tags</h4>
      <ul class="tags">
        <% post.tags.each do |tag| %>
          <li><% link_to tag, tag_path(tag) %></li>
        <% end %>
      </ul>
    <% end %>

    <% if Disqus.enabled? %>
      <div id="disqus_thread" class="disqus-thread">
        <a href="/post/<%= post.id %>#disqus_thread" class="comments"></a>
      </div>
    <% end %>
  </footer>
</article>

app/views/posts/_text.html.erb
<article id="<%= post.id %>">
  <hgroup>
    <h2><a href="<%= post_path(post) %>"><%= post.title %>&nbsp;</a></h2>
    <h3><a href="<%= post.id %>"><%= post.formatted_date %></a></h3>
  </hgroup>

  <%= raw content %>

  <% if show_more %>
    <p><a href="<%= post_path(post) %>" class="read-more-link">read more</a></p>
  <% end %>
  <footer>
    <% if post.tags? %>
      <h4>Tags</h4>
      <ul class="tags">
        <% post.tags.each do |tag| %>
          <li><a href="<%= tag_path(tag) %>"><%= tag %></a></li>
        <% end %>
      </ul>

      <% if Sharethis.enabled? %>
        <div class="sharethis">
          <% if Sharethis.facebook? %>
            <span class='st_facebook_hcount' displayText='Facebook'></span>
          <% end %>

          <% if Sharethis.twitter? %>
            <span class='st_twitter_hcount' displayText='Tweet'></span>
          <% end %>

          <% if Sharethis.linkedin? %>
            <span class='st_linkedin_hcount' displayText='LinkedIn'></span>
          <% end %>

          <% if Sharethis.google_plus? %>
            <span class='st_googleplus_hcount' displayText='Google +'></span>
          <% end %>

          <% if Sharethis.sharethis? %>
            <span class='st_sharethis_hcount' displayText='ShareThis'></span>
          <% end %>

          <% if Sharethis.email? %>
            <span class='st_email_hcount' displayText='Email'></span>
          <% end %>
        </div>
      <% end %>

      <% if Disqus.enabled? %>
        <div id="disqus_thread" class="disqus-thread">
          <a href="/post/<%= post.id %>#disqus_thread" class="comments"></a>
        </div>
      <% end %>
    <% end %>
  </footer>
</article>

<% # @todo (farleyknight@gmail.com): Add Disqus integration %>

app/views/posts/index.html.erb
<% Post.all.each do |post| %>
  <% if post.text? %>
    <%= render partial: "posts/text", locals: {post: post, content: post.excerpt, show_more: true} %>
  <% elsif post.photo? %>
    <%= render partial: "posts/photo", locals: {post: post, image: post.photo, caption: true} %>
  <% else %>
    <%= render partial: "posts/text", locals: {post: post, content: post.excerpt, show_more: true} %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<% content_for :head do %>
  <% if @post.meta_description.present? %>
    <meta name="description" content="<%= @post.meta_description %>" />
  <% end %>

  <% if @post.keywords.present? %>
    <meta name="keywords" content="<%= @post.keywords %>" />
  <% end %>

  <title><%= @post.title %></title>
<% end %>

<section class="main-section blog-section" id="blog-posts">
  <%= render partial: "posts/content", locals: {post: @post, content: @post.body, show_more: false} %>
</section>